### ISSUE TITLE
Massive lag

### ISSUE THREAD

**Issue by evgengoldwar** [reobf/Programmable-Hatches-Mod#82]
![image](https://github.com/user-attachments/assets/3d5f6e5a-1592-4975-a392-69d26b35850e)

![image](https://github.com/user-attachments/assets/7a6afc8b-2714-4f83-885c-20fcad89e2a0)

![image](https://github.com/user-attachments/assets/0996e4e6-103c-409b-9d9b-4d5c7b88e066)

All the chunks where the hatches stand are chunkloaded.

**Comment by reobf** [comment]
I'd be grateful if you could use Spark to get a profile report.

https://www.curseforge.com/minecraft/mc-mods/spark/files/all?page=1&pageSize=20&version=1.7.10&gameVersionTypeId=1&showAlphaFiles=show

**Comment by evgengoldwar** [comment]
https://spark.lucko.me/uGN45Krdki

**Comment by evgengoldwar** [comment]
When I'm in overworld, it's so much worse.

https://spark.lucko.me/KioskvE6WL

![image](https://github.com/user-attachments/assets/79274b22-7f2e-492b-9a61-45c2fd9f07ea)

**Comment by reobf** [comment]
Some performance issue does exist...
Will try to improve in the next release.

**Comment by reobf** [comment]
You might leave this issue open till it's impoved.

**Comment by reobf** [comment]
[programmablehatches-0.0.19p10-GTNH270.jar.zip](https://github.com/user-attachments/files/17411142/programmablehatches-0.0.19p10-GTNH270.jar.zip)
I mean my PC is too slow to run 1 server&1 client at the same time at 20tps.
You might try this one to see if it's improved.

**Comment by reobf** [comment]
![1729169217321](https://github.com/user-attachments/assets/cffda47f-49bc-47d6-83c8-858a16c16641)
Should be much better

**Comment by evgengoldwar** [comment]
> ![1729169217321](https://private-user-images.githubusercontent.com/117543727/377470370-cffda47f-49bc-47d6-83c8-858a16c16641.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjkxODM1ODcsIm5iZiI6MTcyOTE4MzI4NywicGF0aCI6Ii8xMTc1NDM3MjcvMzc3NDcwMzcwLWNmZmRhNDdmLTQ5YmMtNDdkNi04M2M4LTg1OGExNmMxNjY0MS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMDE3JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTAxN1QxNjQxMjdaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1hNWExMWMwNThmMDQzNTMyMDM0ZmJiZTc5ZTU2MjViMmQ2MTdkYmQ4MjRhZGZkYTVmNmFlZTE4OTdhMzljNzJiJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.ZG67y2JM8cm04RxC85MrQjxPURdTs7kOxNP2ZRTdMrQ) Should be much better

Yeah, it's much better.

But going into overworld tps increases 3 times. Before the place of programmable hatches tps was always about 15 mc now 15-20 mc and in overworld 60-100 mc


![image](https://github.com/user-attachments/assets/7618bf63-580b-47e8-84d9-10e5a75048b3)


https://spark.lucko.me/mFuKPC0ct0

**Comment by reobf** [comment]
Uh, are you using GraalVM？
Why not Hotspot?
Seems that there's some problem with GC of Weakreference... caused by my code or GraalVM itself.
I will try to make it clear later tomorrow

**Comment by reobf** [comment]
Or maybe I will just simply provide a config to turn this function off

**Comment by evgengoldwar** [comment]
> Uh, are you using GraalVM？ Why not Hotspot? Seems that there's some problem with GC of Weakreference... caused by my code or GraalVM itself. I will try to make it clear later tomorrow

Yea im using Graal

**Comment by evgengoldwar** [comment]
![image](https://github.com/user-attachments/assets/c57390f7-acbe-4211-b247-b3c1c3dd34f3)

(((

**Comment by reobf** [comment]
[programmablehatches-0.0.19p11-GTNH270.jar.zip](https://github.com/user-attachments/files/17427694/programmablehatches-0.0.19p11-GTNH270.jar.zip)
Cannot reproduce... 
There's some performance issue but not too much(like 10ms+ per tick).
This version allows you to disable this function with command '/proghatch tracking' (need to use this command everytime server restarts).
![c21d52b44f54c584c1dcde1ec7b3599](https://github.com/user-attachments/assets/bf0432ce-11c8-4082-a8e1-a1dbdec24bfe)
Please use this command when the server is laggy.
And when you use this command, two numbers should be shown, please let me know them, thanks!

**Comment by reobf** [comment]
https://github.com/reobf/Programmable-Hatches-Mod/releases/tag/0.0.19p12-beta
Try this one.
'/proghatch tracking' is available but it should be much better without this command.

**Comment by evgengoldwar** [comment]
> https://github.com/reobf/Programmable-Hatches-Mod/releases/tag/0.0.19p12-beta Try this one. '/proghatch tracking' is available but it should be much better without this command.

Overworld when laging
![image](https://github.com/user-attachments/assets/23257c54-d050-401c-87eb-80b05430cf99)

Pd
![image](https://github.com/user-attachments/assets/fdb93375-af44-4034-baee-28cf2db948eb)

**Comment by TimberDimber** [comment]
Pd
![image](https://github.com/user-attachments/assets/ba283ca5-b5cc-48af-b220-8d1b657ca1f8)

Overrworld
![image](https://github.com/user-attachments/assets/bc37ba4f-ad4b-4678-897e-0b713e41feb4)

**Comment by reobf** [comment]
It seems that your chunks are not properly loaded.
![1729295947796](https://github.com/user-attachments/assets/33141d32-5d80-452e-9852-a6ba3ced3fde)
![image](https://github.com/user-attachments/assets/baf26d18-6c21-457b-8e5e-ccc20acc026d)

Some chunks with ME Cable are temporarily loaded and then unloaded, creating tons of grabage ME Cache.
Maybe figure out the the chunks are load them with SU or anchors will help.


300,000+ ME Network Cahces just seems... cursed.

**Comment by reobf** [comment]
> Pd ![image](https://private-user-images.githubusercontent.com/22298720/378031180-ba283ca5-b5cc-48af-b220-8d1b657ca1f8.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjkyOTk3MTEsIm5iZiI6MTcyOTI5OTQxMSwicGF0aCI6Ii8yMjI5ODcyMC8zNzgwMzExODAtYmEyODNjYTUtYjVjYy00OGFmLWIyMjAtOGQxYjY1N2NhMWY4LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEwMTklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMDE5VDAwNTY1MVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWJlZGE1NGNmYTIwZTUwNWE3ZjAyZTI4MmI2YjA2ZDI1MTdkMmFmZjMxYTkwYTBjNDQ1MTMyOWY3MDBiYTA2Y2QmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.LYsEyewwhCVRyjSNX5Qpl5ILliwR8I9Mt1BobDpsKe4)
> 
> Overrworld ![image](https://private-user-images.githubusercontent.com/22298720/378031236-bc37ba4f-ad4b-4678-897e-0b713e41feb4.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjkyOTk3MTEsIm5iZiI6MTcyOTI5OTQxMSwicGF0aCI6Ii8yMjI5ODcyMC8zNzgwMzEyMzYtYmMzN2JhNGYtYWQ0Yi00Njc4LTg5N2UtMGI3MTNlNDFmZWI0LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEwMTklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMDE5VDAwNTY1MVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWRjNWY2ZjFmNDZiMWVjNWFmY2NiMWM4MGQ2MGFhYTU5NTQ0NzExOWFhOTEwMTkyZTQ5ZjE4ODFiMGIyY2NhOGQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.xX9VrNVRk9PW_RV7_teC-MTujFYxCpblB4b9kUhFIO4)
> 
> Java8

Same save file as @evgengoldwar's?
Or its your own one?

**Comment by TimberDimber** [comment]
> > Pd ![image](https://private-user-images.githubusercontent.com/22298720/378031180-ba283ca5-b5cc-48af-b220-8d1b657ca1f8.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjkyOTk3MTEsIm5iZiI6MTcyOTI5OTQxMSwicGF0aCI6Ii8yMjI5ODcyMC8zNzgwMzExODAtYmEyODNjYTUtYjVjYy00OGFmLWIyMjAtOGQxYjY1N2NhMWY4LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEwMTklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMDE5VDAwNTY1MVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWJlZGE1NGNmYTIwZTUwNWE3ZjAyZTI4MmI2YjA2ZDI1MTdkMmFmZjMxYTkwYTBjNDQ1MTMyOWY3MDBiYTA2Y2QmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.LYsEyewwhCVRyjSNX5Qpl5ILliwR8I9Mt1BobDpsKe4)
> > Overrworld ![image](https://private-user-images.githubusercontent.com/22298720/378031236-bc37ba4f-ad4b-4678-897e-0b713e41feb4.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjkyOTk3MTEsIm5iZiI6MTcyOTI5OTQxMSwicGF0aCI6Ii8yMjI5ODcyMC8zNzgwMzEyMzYtYmMzN2JhNGYtYWQ0Yi00Njc4LTg5N2UtMGI3MTNlNDFmZWI0LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEwMTklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMDE5VDAwNTY1MVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWRjNWY2ZjFmNDZiMWVjNWFmY2NiMWM4MGQ2MGFhYTU5NTQ0NzExOWFhOTEwMTkyZTQ5ZjE4ODFiMGIyY2NhOGQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.xX9VrNVRk9PW_RV7_teC-MTujFYxCpblB4b9kUhFIO4)
> > Java8
> 
> Same save file as @evgengoldwar's? Or its your own one?

My own. Will check his in 5 mins

**Comment by TimberDimber** [comment]
> https://imgur.com/a/uaquGmT <-link is dead?

https://www.dropbox.com/scl/fi/0swcl09et0drbshk3jtop/uYdCNGt.mp4

**Comment by TimberDimber** [comment]
> Same save file as @evgengoldwar's? Or its your own one?
PD evegn's world
![image](https://github.com/user-attachments/assets/f9591ac9-7cd6-4b33-b36c-669ba21d2d48)

**Comment by TimberDimber** [comment]
And his over.
![image](https://github.com/user-attachments/assets/4c494762-b35b-4c66-b887-de6184b4d778)

**Comment by TimberDimber** [comment]
And... after 5 minutes of lags take craft-report

java.lang.OutOfMemoryError: GC overhead limit exceeded
    at java.util.HashMap.newNode(Unknown Source)
    at java.util.HashMap.putVal(Unknown Source)
    at java.util.HashMap.put(Unknown Source)
    at java.util.HashSet.add(Unknown Source)
    at appeng.me.cache.EnergyGridCache.extractAEPower(EnergyGridCache.java:232)
    at appeng.parts.networking.PartQuartzFiber.extractAEPower(PartQuartzFiber.java:157)
    at appeng.me.cache.EnergyGridCache.extractFromOtherGrids(EnergyGridCache.java:293)
    at appeng.me.cache.EnergyGridCache.extractAEPower(EnergyGridCache.java:269)
    at appeng.parts.networking.PartQuartzFiber.extractAEPower(PartQuartzFiber.java:157)
    at appeng.me.cache.EnergyGridCache.extractFromOtherGrids(EnergyGridCache.java:293)
    at appeng.me.cache.EnergyGridCache.extractAEPower(EnergyGridCache.java:269)
    at appeng.parts.networking.PartQuartzFiber.extractAEPower(PartQuartzFiber.java:157)
    at appeng.me.cache.EnergyGridCache.extractFromOtherGrids(EnergyGridCache.java:293)
    at appeng.me.cache.EnergyGridCache.extractAEPower(EnergyGridCache.java:269)
    at appeng.parts.networking.PartQuartzFiber.extractAEPower(PartQuartzFiber.java:157)
    at appeng.me.cache.EnergyGridCache.extractFromOtherGrids(EnergyGridCache.java:293)
    at appeng.me.cache.EnergyGridCache.extractAEPower(EnergyGridCache.java:269)
    at appeng.parts.networking.PartQuartzFiber.extractAEPower(PartQuartzFiber.java:172)
    at appeng.me.cache.EnergyGridCache.extractFromOtherGrids(EnergyGridCache.java:293)
    at appeng.me.cache.EnergyGridCache.extractAEPower(EnergyGridCache.java:269)
    at appeng.parts.networking.PartQuartzFiber.extractAEPower(PartQuartzFiber.java:157)
    at appeng.me.cache.EnergyGridCache.extractFromOtherGrids(EnergyGridCache.java:293)
    at appeng.me.cache.EnergyGridCache.extractAEPower(EnergyGridCache.java:269)
    at appeng.parts.networking.PartQuartzFiber.extractAEPower(PartQuartzFiber.java:157)
    at appeng.me.cache.EnergyGridCache.extractFromOtherGrids(EnergyGridCache.java:293)
    at appeng.me.cache.EnergyGridCache.extractAEPower(EnergyGridCache.java:269)
    at appeng.parts.networking.PartQuartzFiber.extractAEPower(PartQuartzFiber.java:157)
    at appeng.me.cache.EnergyGridCache.extractFromOtherGrids(EnergyGridCache.java:293)
    at appeng.me.cache.EnergyGridCache.extractAEPower(EnergyGridCache.java:269)
    at appeng.parts.networking.PartQuartzFiber.extractAEPower(PartQuartzFiber.java:157)
    at appeng.me.cache.EnergyGridCache.extractFromOtherGrids(EnergyGridCache.java:293)
    at appeng.me.cache.EnergyGridCache.extractAEPower(EnergyGridCache.java:269)

**Comment by reobf** [comment]
I will remove the tracking function in the next release.
This function is too useless anyway.
But I believe that there's some problem with ME Network design and not likely to be solved with this function begin removed.

**Comment by reobf** [comment]
> And... after 5 minutes of lags take craft-report
> 
> ```
> [04:20:57] [Server thread/ERROR] [FML]: Exception caught during firing event cpw.mods.fml.common.gameevent.TickEvent$ServerTickEvent@27146bf1:
> java.lang.OutOfMemoryError: GC overhead limit exceeded
> 	at java.util.HashMap.newNode(Unknown Source) ~[?:1.8.0_421]
> 	at java.util.HashMap.putVal(Unknown Source) ~[?:1.8.0_421]
> 	at java.util.HashMap.put(Unknown Source) ~[?:1.8.0_421]
> 	at java.util.HashSet.add(Unknown Source) ~[?:1.8.0_421]
> 	at appeng.me.cache.EnergyGridCache.extractAEPower(EnergyGridCache.java:232) ~[EnergyGridCache.class:?]
> 	at appeng.parts.networking.PartQuartzFiber.extractAEPower(PartQuartzFiber.java:157) ~[PartQuartzFiber.class:?]
> 	at appeng.me.cache.EnergyGridCache.extractFromOtherGrids(EnergyGridCache.java:293) ~[EnergyGridCache.class:?]
> 	at appeng.me.cache.EnergyGridCache.extractAEPower(EnergyGridCache.java:269) ~[EnergyGridCache.class:?]
> 	at appeng.parts.networking.PartQuartzFiber.extractAEPower(PartQuartzFiber.java:157) ~[PartQuartzFiber.class:?]
> 	at appeng.me.cache.EnergyGridCache.extractFromOtherGrids(EnergyGridCache.java:293) ~[EnergyGridCache.class:?]
> 	at appeng.me.cache.EnergyGridCache.extractAEPower(EnergyGridCache.java:269) ~[EnergyGridCache.class:?]
> 	at appeng.parts.networking.PartQuartzFiber.extractAEPower(PartQuartzFiber.java:157) ~[PartQuartzFiber.class:?]
> 	at appeng.me.cache.EnergyGridCache.extractFromOtherGrids(EnergyGridCache.java:293) ~[EnergyGridCache.class:?]
> 	at appeng.me.cache.EnergyGridCache.extractAEPower(EnergyGridCache.java:269) ~[EnergyGridCache.class:?]
> 	at appeng.parts.networking.PartQuartzFiber.extractAEPower(PartQuartzFiber.java:157) ~[PartQuartzFiber.class:?]
> 	at appeng.me.cache.EnergyGridCache.extractFromOtherGrids(EnergyGridCache.java:293) ~[EnergyGridCache.class:?]
> 	at appeng.me.cache.EnergyGridCache.extractAEPower(EnergyGridCache.java:269) ~[EnergyGridCache.class:?]
> 	at appeng.parts.networking.PartQuartzFiber.extractAEPower(PartQuartzFiber.java:172) ~[PartQuartzFiber.class:?]
> 	at appeng.me.cache.EnergyGridCache.extractFromOtherGrids(EnergyGridCache.java:293) ~[EnergyGridCache.class:?]
> 	at appeng.me.cache.EnergyGridCache.extractAEPower(EnergyGridCache.java:269) ~[EnergyGridCache.class:?]
> 	at appeng.parts.networking.PartQuartzFiber.extractAEPower(PartQuartzFiber.java:157) ~[PartQuartzFiber.class:?]
> 	at appeng.me.cache.EnergyGridCache.extractFromOtherGrids(EnergyGridCache.java:293) ~[EnergyGridCache.class:?]
> 	at appeng.me.cache.EnergyGridCache.extractAEPower(EnergyGridCache.java:269) ~[EnergyGridCache.class:?]
> 	at appeng.parts.networking.PartQuartzFiber.extractAEPower(PartQuartzFiber.java:157) ~[PartQuartzFiber.class:?]
> 	at appeng.me.cache.EnergyGridCache.extractFromOtherGrids(EnergyGridCache.java:293) ~[EnergyGridCache.class:?]
> 	at appeng.me.cache.EnergyGridCache.extractAEPower(EnergyGridCache.java:269) ~[EnergyGridCache.class:?]
> 	at appeng.parts.networking.PartQuartzFiber.extractAEPower(PartQuartzFiber.java:157) ~[PartQuartzFiber.class:?]
> 	at appeng.me.cache.EnergyGridCache.extractFromOtherGrids(EnergyGridCache.java:293) ~[EnergyGridCache.class:?]
> 	at appeng.me.cache.EnergyGridCache.extractAEPower(EnergyGridCache.java:269) ~[EnergyGridCache.class:?]
> 	at appeng.parts.networking.PartQuartzFiber.extractAEPower(PartQuartzFiber.java:157) ~[PartQuartzFiber.class:?]
> 	at appeng.me.cache.EnergyGridCache.extractFromOtherGrids(EnergyGridCache.java:293) ~[EnergyGridCache.class:?]
> 	at appeng.me.cache.EnergyGridCache.extractAEPower(EnergyGridCache.java:269) ~[EnergyGridCache.class:?]
> [04:20:57] [Server thread/ERROR] [FML]: Index: 69 Listeners:
> [04:20:57] [Server thread/ERROR] [FML]: 0: HIGHEST
> [04:20:57] [Server thread/ERROR] [FML]: 1: ASM: gtPlusPlus.xmod.gregtech.common.helpers.ChargingHelper@4402ebb7 onServerTick(Lcpw/mods/fml/common/gameevent/TickEvent$ServerTickEvent;)V
> [04:20:57] [Server thread/ERROR] [FML]: 2: ASM: toast.specialMobs.TickHandler@48307adb onServerTick(Lcpw/mods/fml/common/gameevent/TickEvent$ServerTickEvent;)V
> [04:20:57] [Server thread/ERROR] [FML]: 3: HIGH
> [04:20:57] [Server thread/ERROR] [FML]: 4: ASM: reobf.proghatches.main.MyMod@11f7c8e0 tick(Lcpw/mods/fml/common/gameevent/TickEvent$ServerTickEvent;)V
> [04:20:57] [Server thread/ERROR] [FML]: 5: ASM: reobf.proghatches.main.MyMod@11f7c8e0 pretick(Lcpw/mods/fml/common/gameevent/TickEvent$ServerTickEvent;)V
> [04:20:57] [Server thread/ERROR] [FML]: 6: NORMAL
> [04:20:57] [Server thread/ERROR] [FML]: 7: ASM: gregtech.common.GTClient@2d52f384 onServerTickEvent(Lcpw/mods/fml/common/gameevent/TickEvent$ServerTickEvent;)V
> [04:20:57] [Server thread/ERROR] [FML]: 8: ASM: ic2.core.TickHandler@4f2df133 onServerTick(Lcpw/mods/fml/common/gameevent/TickEvent$ServerTickEvent;)V
> [04:20:57] [Server thread/ERROR] [FML]: 9: ASM: org.embeddedt.archaicfix.proxy.ClientProxy@ad31174 onTick(Lcpw/mods/fml/common/gameevent/TickEvent$ServerTickEvent;)V
> [04:20:57] [Server thread/ERROR] [FML]: 10: ASM: com.mitchej123.hodgepodge.HodgepodgeEventHandler@7b100eed onServerTick(Lcpw/mods/fml/common/gameevent/TickEvent$ServerTickEvent;)V
> [04:20:57] [Server thread/ERROR] [FML]: 11: ASM: com.gtnewhorizons.angelica.proxy.ClientProxy@5397d652 onTick(Lcpw/mods/fml/common/gameevent/TickEvent$ServerTickEvent;)V
> [04:20:57] [Server thread/ERROR] [FML]: 12: ASM: mods.railcraft.client.sounds.SoundLimiterTicker@445585ba tick(Lcpw/mods/fml/common/gameevent/TickEvent$ServerTickEvent;)V
> [04:20:57] [Server thread/ERROR] [FML]: 13: ASM: team.chisel.item.chisel.ChiselController@66460ab6 openQueuedGui(Lcpw/mods/fml/common/gameevent/TickEvent$ServerTickEvent;)V
> [04:20:57] [Server thread/ERROR] [FML]: 14: ASM: chylex.hee.mechanics.charms.handler.CharmPouchHandler@625fef9a onServerTick(Lcpw/mods/fml/common/gameevent/TickEvent$ServerTickEvent;)V
> [04:20:57] [Server thread/ERROR] [FML]: 15: ASM: chylex.hee.mechanics.misc.TempleEvents@34200610 onServerTick(Lcpw/mods/fml/common/gameevent/TickEvent$ServerTickEvent;)V
> [04:20:57] [Server thread/ERROR] [FML]: 16: ASM: crazypants.enderio.machine.spawner.BlockPoweredSpawner@4c4797be onServerTick(Lcpw/mods/fml/common/gameevent/TickEvent$ServerTickEvent;)V
> [04:20:57] [Server thread/ERROR] [FML]: 17: ASM: crazypants.enderio.conduit.ConduitNetworkTickHandler@16014f2b onServerTick(Lcpw/mods/fml/common/gameevent/TickEvent$ServerTickEvent;)V
> [04:20:57] [Server thread/ERROR] [FML]: 18: ASM: betterquesting.handlers.EventHandler@47507f1f onServerTick(Lcpw/mods/fml/common/gameevent/TickEvent$ServerTickEvent;)V
> [04:20:57] [Server thread/ERROR] [FML]: 19: ASM: bq_standard.handlers.EventHandler@661fd307 onServerTick(Lcpw/mods/fml/common/gameevent/TickEvent$ServerTickEvent;)V
> [04:20:57] [Server thread/ERROR] [FML]: 20: ASM: com.cleanroommc.modularui.factory.GuiManager@4dc9ca58 onTick(Lcpw/mods/fml/common/gameevent/TickEvent$ServerTickEvent;)V
> [04:20:57] [Server thread/ERROR] [FML]: 21: ASM: com.emoniph.witchery.common.ServerTickEvents@24b7e201 onServerTick(Lcpw/mods/fml/common/gameevent/TickEvent$ServerTickEvent;)V
> [04:20:57] [Server thread/ERROR] [FML]: 22: ASM: com.brandon3055.brandonscore.common.handlers.ProcessHandler@77f4a737 onServerTick(Lcpw/mods/fml/common/gameevent/TickEvent$ServerTickEvent;)V
> [04:20:57] [Server thread/ERROR] [FML]: 23: ASM: com.thecodewarrior.catwalks.util.ClientProxy@62134d3c onServerTick(Lcpw/mods/fml/common/gameevent/TickEvent$ServerTickEvent;)V
> [04:20:57] [Server thread/ERROR] [FML]: 24: ASM: codechicken.enderstorage.storage.liquid.TankSynchroniser@20c50997 tickEnd(Lcpw/mods/fml/common/gameevent/TickEvent$ServerTickEvent;)V
> [04:20:57] [Server thread/ERROR] [FML]: 25: ASM: DummyCore.Utils.DummyEventHandler@496eddaa onServerTick(Lcpw/mods/fml/common/gameevent/TickEvent$ServerTickEvent;)V
> [04:20:57] [Server thread/ERROR] [FML]: 26: ASM: tectech.TecTechEventHandlers@72235527 onServerTickEnd(Lcpw/mods/fml/common/gameevent/TickEvent$ServerTickEvent;)V
> [04:20:57] [Server thread/ERROR] [FML]: 27: ASM: taintedmagic.common.items.tools.ItemKatana$EventHandler@16a05e75 onServerTick(Lcpw/mods/fml/common/gameevent/TickEvent$ServerTickEvent;)V
> [04:20:57] [Server thread/ERROR] [FML]: 28: ASM: com.chaosthedude.naturescompass.proxy.ServerTickHandler@51f5fd74 onServerTick(Lcpw/mods/fml/common/gameevent/TickEvent$ServerTickEvent;)V
> [04:20:57] [Server thread/ERROR] [FML]: 29: ASM: INSTANCE tickEnd(Lcpw/mods/fml/common/gameevent/TickEvent$ServerTickEvent;)V
> [04:20:57] [Server thread/ERROR] [FML]: 30: ASM: serverutils.handlers.ServerUtilitiesServerEventHandler@30d550d3 onServerTick(Lcpw/mods/fml/common/gameevent/TickEvent$ServerTickEvent;)V
> [04:20:57] [Server thread/ERROR] [FML]: 31: ASM: gcewing.sg.SGCraft@2abb01d8 onServerTick(Lcpw/mods/fml/common/gameevent/TickEvent$ServerTickEvent;)V
> [04:20:57] [Server thread/ERROR] [FML]: 32: ASM: codechicken.wirelessredstone.core.WRCoreEventHandler@1932f4ab serverTick(Lcpw/mods/fml/common/gameevent/TickEvent$ServerTickEvent;)V
> [04:20:57] [Server thread/ERROR] [FML]: 33: ASM: buildcraft.core.tablet.manager.TabletManagerServer@bd63316 serverTick(Lcpw/mods/fml/common/gameevent/TickEvent$ServerTickEvent;)V
> [04:20:57] [Server thread/ERROR] [FML]: 34: ASM: micdoodle8.mods.galacticraft.planets.asteroids.tick.AsteroidsTickHandlerServer@9c75abb onServerTick(Lcpw/mods/fml/common/gameevent/TickEvent$ServerTickEvent;)V
> [04:20:57] [Server thread/ERROR] [FML]: 35: ASM: com.enderio.core.common.util.Scheduler@755a3634 onServerTick(Lcpw/mods/fml/common/gameevent/TickEvent$ServerTickEvent;)V
> [04:20:57] [Server thread/ERROR] [FML]: 36: ASM: mods.natura.Natura@575bfc1e tickEvent(Lcpw/mods/fml/common/gameevent/TickEvent$ServerTickEvent;)V
> [04:20:57] [Server thread/ERROR] [FML]: 37: ASM: crazypants.enderio.CommonProxy$TickTimer@6d47f325 onTick(Lcpw/mods/fml/common/gameevent/TickEvent$ServerTickEvent;)V
> [04:20:57] [Server thread/ERROR] [FML]: 38: ASM: thaumic.tinkerer.common.potion.PotionEffectHandler@141eb79c onTick(Lcpw/mods/fml/common/gameevent/TickEvent$ServerTickEvent;)V
> [04:20:57] [Server thread/ERROR] [FML]: 39: ASM: li.cil.oc.common.EventHandler$@44c2f7ff onServerTick(Lcpw/mods/fml/common/gameevent/TickEvent$ServerTickEvent;)Ljava/lang/Object;
> [04:20:57] [Server thread/ERROR] [FML]: 40: ASM: li.cil.oc.common.asm.SimpleComponentTickHandler@1292e24e onTick(Lcpw/mods/fml/common/gameevent/TickEvent$ServerTickEvent;)V
> [04:20:57] [Server thread/ERROR] [FML]: 41: ASM: li.cil.oc.common.item.Tablet$@585058d6 onServerTick(Lcpw/mods/fml/common/gameevent/TickEvent$ServerTickEvent;)V
> [04:20:57] [Server thread/ERROR] [FML]: 42: ASM: pl.asie.computronics.tape.PortableDriveManager@4001b079 onServerTick(Lcpw/mods/fml/common/gameevent/TickEvent$ServerTickEvent;)V
> [04:20:57] [Server thread/ERROR] [FML]: 43: ASM: pl.asie.computronics.oc.driver.DriverBoardBoom$BoomHandler@217e4d6b onServerTick(Lcpw/mods/fml/common/gameevent/TickEvent$ServerTickEvent;)V
> [04:20:57] [Server thread/ERROR] [FML]: 44: ASM: de.keridos.floodlights.core.FMLEventListener@53a52c3 onServerTick(Lcpw/mods/fml/common/gameevent/TickEvent$ServerTickEvent;)V
> [04:20:57] [Server thread/ERROR] [FML]: 45: ASM: makeo.gadomancy.common.events.EventHandlerWorld@358be448 on(Lcpw/mods/fml/common/gameevent/TickEvent$ServerTickEvent;)V
> [04:20:57] [Server thread/ERROR] [FML]: 46: ASM: openblocks.common.ServerTickHandler@35a3198e onServerTick(Lcpw/mods/fml/common/gameevent/TickEvent$ServerTickEvent;)V
> [04:20:57] [Server thread/ERROR] [FML]: 47: ASM: com.sinthoras.hydroenergy.hooks.HEHooksFML@70a18193 onEvent(Lcpw/mods/fml/common/gameevent/TickEvent$ServerTickEvent;)V
> [04:20:57] [Server thread/ERROR] [FML]: 48: ASM: INSTANCE tickServer(Lcpw/mods/fml/common/gameevent/TickEvent$ServerTickEvent;)V
> [04:20:57] [Server thread/ERROR] [FML]: 49: ASM: logisticspipes.ticks.LPTickHandler@33472672 serverTick(Lcpw/mods/fml/common/gameevent/TickEvent$ServerTickEvent;)V
> [04:20:57] [Server thread/ERROR] [FML]: 50: ASM: logisticspipes.ticks.QueuedTasks@558922df tickEnd(Lcpw/mods/fml/common/gameevent/TickEvent$ServerTickEvent;)V
> [04:20:57] [Server thread/ERROR] [FML]: 51: ASM: gcewing.projectblue.ProjectBlue@4374ca69 onServerTick(Lcpw/mods/fml/common/gameevent/TickEvent$ServerTickEvent;)V
> [04:20:57] [Server thread/ERROR] [FML]: 52: ASM: com.github.lunatrius.schematica.handler.QueueTickHandler@75a1681e onServerTick(Lcpw/mods/fml/common/gameevent/TickEvent$ServerTickEvent;)V
> [04:20:57] [Server thread/ERROR] [FML]: 53: ASM: com.github.lunatrius.schematica.handler.DownloadHandler@c9a3af onServerTick(Lcpw/mods/fml/common/gameevent/TickEvent$ServerTickEvent;)V
> [04:20:57] [Server thread/ERROR] [FML]: 54: ASM: ru.npo6ka.sleepingbag.EventHandler@9f99365 onTick(Lcpw/mods/fml/common/gameevent/TickEvent$ServerTickEvent;)V
> [04:20:57] [Server thread/ERROR] [FML]: 55: ASM: com.Nxer.TwistSpaceTechnology.event.TickingEvent@34a15bed onTick(Lcpw/mods/fml/common/gameevent/TickEvent$ServerTickEvent;)V
> [04:20:57] [Server thread/ERROR] [FML]: 56: ASM: codechicken.wirelessredstone.addons.WRAddonEventHandler@5b8cdfd7 serverTick(Lcpw/mods/fml/common/gameevent/TickEvent$ServerTickEvent;)V
> [04:20:57] [Server thread/ERROR] [FML]: 57: ASM: codechicken.multipart.handler.MultipartEventHandler$@65a3dc58 serverTick(Lcpw/mods/fml/common/gameevent/TickEvent$ServerTickEvent;)V
> [04:20:57] [Server thread/ERROR] [FML]: 58: ASM: com.rwtema.extrautils.CommandTPSTimer@1aeb38fd onServerTick(Lcpw/mods/fml/common/gameevent/TickEvent$ServerTickEvent;)V
> [04:20:57] [Server thread/ERROR] [FML]: 59: ASM: micdoodle8.mods.galacticraft.core.tick.TickHandlerServer@978b3d4 onServerTick(Lcpw/mods/fml/common/gameevent/TickEvent$ServerTickEvent;)V
> [04:20:57] [Server thread/ERROR] [FML]: 60: ASM: de.katzenpapst.amunra.tick.TickHandlerServer@49b9cec0 onServerTick(Lcpw/mods/fml/common/gameevent/TickEvent$ServerTickEvent;)V
> [04:20:57] [Server thread/ERROR] [FML]: 61: ASM: crazypants.enderzoo.spawn.MobSpawnEventHandler@3023f8e2 onServerTick(Lcpw/mods/fml/common/gameevent/TickEvent$ServerTickEvent;)V
> [04:20:57] [Server thread/ERROR] [FML]: 62: ASM: mrtjp.relocation.RelocationEventHandler$@1160f926 serverTick(Lcpw/mods/fml/common/gameevent/TickEvent$ServerTickEvent;)V
> [04:20:57] [Server thread/ERROR] [FML]: 63: ASM: com.falsepattern.laggoggles.profiler.TickCounter@6f642612 addTick(Lcpw/mods/fml/common/gameevent/TickEvent$ServerTickEvent;)V
> [04:20:57] [Server thread/ERROR] [FML]: 64: ASM: vazkii.botania.common.block.BlockPistonRelay@6e56142a tickEnd(Lcpw/mods/fml/common/gameevent/TickEvent;)V
> [04:20:57] [Server thread/ERROR] [FML]: 65: ASM: com.brandon3055.draconicevolution.common.handler.FMLEventHandler@2e29e874 serverTickEvent(Lcpw/mods/fml/common/gameevent/TickEvent;)V
> [04:20:57] [Server thread/ERROR] [FML]: 66: ASM: lumien.randomthings.Handler.RTTickHandler@1cd193f3 tick(Lcpw/mods/fml/common/gameevent/TickEvent;)V
> [04:20:57] [Server thread/ERROR] [FML]: 67: ASM: remoteio.common.tracker.BlockTracker@20a60380 onWorldTick(Lcpw/mods/fml/common/gameevent/TickEvent;)V
> [04:20:57] [Server thread/ERROR] [FML]: 68: ASM: com.sk89q.worldedit.forge.ThreadSafeCache@39bfa98f tickStart(Lcpw/mods/fml/common/gameevent/TickEvent;)V
> [04:20:57] [Server thread/ERROR] [FML]: 69: ASM: appeng.hooks.TickHandler@2b3663f5 onTick(Lcpw/mods/fml/common/gameevent/TickEvent;)V
> [04:20:57] [Server thread/ERROR] [FML]: 70: ASM: thaumic.tinkerer.client.core.handler.ClientTickHandler@727c2ba tickEnd(Lcpw/mods/fml/common/gameevent/TickEvent;)V
> [04:20:57] [Server thread/ERROR] [FML]: 71: ASM: com.creativemd.creativecore.common.event.TickHandler@ff070d7 onEventTick(Lcpw/mods/fml/common/gameevent/TickEvent;)V
> [04:20:57] [Server thread/ERROR] [FML]: 72: ASM: com.sinthoras.visualprospecting.hooks.HooksFML@13ae95df onEvent(Lcpw/mods/fml/common/gameevent/TickEvent;)V
> [04:20:57] [Server thread/ERROR] [FML]: 73: ASM: com.github.hexosse.wecuife.j.b@3cd37ed4 a(Lcpw/mods/fml/common/gameevent/TickEvent;)V
> [04:20:57] [Server thread/ERROR]: Encountered an unexpected exception
> java.lang.OutOfMemoryError: GC overhead limit exceeded
> 	at java.util.HashMap.newNode(Unknown Source) ~[?:1.8.0_421]
> 	at java.util.HashMap.putVal(Unknown Source) ~[?:1.8.0_421]
> 	at java.util.HashMap.put(Unknown Source) ~[?:1.8.0_421]
> 	at java.util.HashSet.add(Unknown Source) ~[?:1.8.0_421]
> 	at appeng.me.cache.EnergyGridCache.extractAEPower(EnergyGridCache.java:232) ~[EnergyGridCache.class:?]
> 	at appeng.parts.networking.PartQuartzFiber.extractAEPower(PartQuartzFiber.java:157) ~[PartQuartzFiber.class:?]
> 	at appeng.me.cache.EnergyGridCache.extractFromOtherGrids(EnergyGridCache.java:293) ~[EnergyGridCache.class:?]
> 	at appeng.me.cache.EnergyGridCache.extractAEPower(EnergyGridCache.java:269) ~[EnergyGridCache.class:?]
> 	at appeng.parts.networking.PartQuartzFiber.extractAEPower(PartQuartzFiber.java:157) ~[PartQuartzFiber.class:?]
> 	at appeng.me.cache.EnergyGridCache.extractFromOtherGrids(EnergyGridCache.java:293) ~[EnergyGridCache.class:?]
> 	at appeng.me.cache.EnergyGridCache.extractAEPower(EnergyGridCache.java:269) ~[EnergyGridCache.class:?]
> 	at appeng.parts.networking.PartQuartzFiber.extractAEPower(PartQuartzFiber.java:157) ~[PartQuartzFiber.class:?]
> 	at appeng.me.cache.EnergyGridCache.extractFromOtherGrids(EnergyGridCache.java:293) ~[EnergyGridCache.class:?]
> 	at appeng.me.cache.EnergyGridCache.extractAEPower(EnergyGridCache.java:269) ~[EnergyGridCache.class:?]
> 	at appeng.parts.networking.PartQuartzFiber.extractAEPower(PartQuartzFiber.java:157) ~[PartQuartzFiber.class:?]
> 	at appeng.me.cache.EnergyGridCache.extractFromOtherGrids(EnergyGridCache.java:293) ~[EnergyGridCache.class:?]
> 	at appeng.me.cache.EnergyGridCache.extractAEPower(EnergyGridCache.java:269) ~[EnergyGridCache.class:?]
> 	at appeng.parts.networking.PartQuartzFiber.extractAEPower(PartQuartzFiber.java:172) ~[PartQuartzFiber.class:?]
> 	at appeng.me.cache.EnergyGridCache.extractFromOtherGrids(EnergyGridCache.java:293) ~[EnergyGridCache.class:?]
> 	at appeng.me.cache.EnergyGridCache.extractAEPower(EnergyGridCache.java:269) ~[EnergyGridCache.class:?]
> 	at appeng.parts.networking.PartQuartzFiber.extractAEPower(PartQuartzFiber.java:157) ~[PartQuartzFiber.class:?]
> 	at appeng.me.cache.EnergyGridCache.extractFromOtherGrids(EnergyGridCache.java:293) ~[EnergyGridCache.class:?]
> 	at appeng.me.cache.EnergyGridCache.extractAEPower(EnergyGridCache.java:269) ~[EnergyGridCache.class:?]
> 	at appeng.parts.networking.PartQuartzFiber.extractAEPower(PartQuartzFiber.java:157) ~[PartQuartzFiber.class:?]
> 	at appeng.me.cache.EnergyGridCache.extractFromOtherGrids(EnergyGridCache.java:293) ~[EnergyGridCache.class:?]
> 	at appeng.me.cache.EnergyGridCache.extractAEPower(EnergyGridCache.java:269) ~[EnergyGridCache.class:?]
> 	at appeng.parts.networking.PartQuartzFiber.extractAEPower(PartQuartzFiber.java:157) ~[PartQuartzFiber.class:?]
> 	at appeng.me.cache.EnergyGridCache.extractFromOtherGrids(EnergyGridCache.java:293) ~[EnergyGridCache.class:?]
> 	at appeng.me.cache.EnergyGridCache.extractAEPower(EnergyGridCache.java:269) ~[EnergyGridCache.class:?]
> 	at appeng.parts.networking.PartQuartzFiber.extractAEPower(PartQuartzFiber.java:157) ~[PartQuartzFiber.class:?]
> 	at appeng.me.cache.EnergyGridCache.extractFromOtherGrids(EnergyGridCache.java:293) ~[EnergyGridCache.class:?]
> 	at appeng.me.cache.EnergyGridCache.extractAEPower(EnergyGridCache.java:269) ~[EnergyGridCache.class:?]
> ```

No idea...
Can you reproduce with my mod removed?

**Comment by reobf** [comment]
Or can you upload the savefile?

**Comment by reobf** [comment]
Did you copy ME Network with WorldEdit or something similiar?
I think WorldEdit might have some problem handling AE Tiles NBT.

**Comment by evgengoldwar** [comment]
> Or can you upload the game savefile?

https://drive.google.com/file/d/1rGopgNde807_IW9g4rQVtCsq52U3yJlk/view?usp=drive_link

My world

**Comment by reobf** [comment]
Thanks!

**Comment by reobf** [comment]
Did you use WorldEdit in that savefile?

**Comment by evgengoldwar** [comment]
> Did you use WorldEdit in that savefile(to copy structures with AE blocks)?

No

**Comment by TimberDimber** [comment]
> No idea... Can you reproduce with my mod removed?

PD
![image](https://github.com/user-attachments/assets/9ee0cc06-5d3c-4043-967f-4cb876481240)
![image](https://github.com/user-attachments/assets/07486c33-7d26-4a56-b79f-d8563e51d0c3)


Over
![image](https://github.com/user-attachments/assets/a8fd2dae-27a5-4f3f-b4f2-3fafd1e9f0bb)

**Comment by TimberDimber** [comment]
So... I checked without a mod.
It looks like this is not a problem with your mod, but with the design of evgen's "base" and an omission of the ae mod itself. After some time of measurements, it turned out that even a switched off and unloaded AE tries to perform calculations and because it is not fully loaded (there is no chunk loading in over.) it creates lags. After deleting the entire "old" base or flying away from it and unloading - the lags disappear.
However, evgen complains that lags are still present in PD and tick rate drops occur from time to time, after checking I really got them, but this is due to the design of the "base" and lags are created by AE itself.

**Comment by TimberDimber** [comment]
And get this in console time by time.
```
java.util.concurrent.CancellationException
	at java.util.concurrent.CompletableFuture.cancel(Unknown Source) [?:1.8.0_421]
	at me.jellysquid.mods.sodium.client.render.chunk.compile.ChunkBuilder.stopWorkers(ChunkBuilder.java:158) [ChunkBuilder.class:?]
	at me.jellysquid.mods.sodium.client.render.chunk.ChunkRenderManager.destroy(ChunkRenderManager.java:633) [ChunkRenderManager.class:?]
	at me.jellysquid.mods.sodium.client.render.SodiumWorldRenderer.initRenderer(SodiumWorldRenderer.java:296) [SodiumWorldRenderer.class:?]
	at me.jellysquid.mods.sodium.client.render.SodiumWorldRenderer.reload(SodiumWorldRenderer.java:291) [SodiumWorldRenderer.class:?]
	at net.minecraft.client.renderer.RenderGlobal.reload(RenderGlobal.java:5744) [bma.class:?]
	at net.minecraft.client.renderer.RenderGlobal.handler$zfk000$angelica$onReload(RenderGlobal.java:5737) [bma.class:?]
	at net.minecraft.client.renderer.RenderGlobal.func_72712_a(RenderGlobal.java:5766) [bma.class:?]
	at net.minecraft.client.renderer.RenderGlobal.func_72732_a(RenderGlobal.java:294) [bma.class:?]
	at net.minecraft.client.Minecraft.func_71353_a(Minecraft.java:2216) [bao.class:?]
	at net.minecraft.client.Minecraft.func_71403_a(Minecraft.java:2146) [bao.class:?]
	at net.minecraft.client.network.NetHandlerPlayClient.func_147280_a(NetHandlerPlayClient.java:874) [bjb.class:?]
	at net.minecraft.network.play.server.S07PacketRespawn.func_148833_a(SourceFile:32) [hs.class:?]
	at net.minecraft.network.play.server.S07PacketRespawn.func_148833_a(SourceFile:13) [hs.class:?]
	at net.minecraft.network.NetworkManager.func_74428_b(NetworkManager.java:212) [ej.class:?]
	at net.minecraft.client.multiplayer.PlayerControllerMP.func_78765_e(PlayerControllerMP.java:273) [bje.class:?]
	at net.minecraft.client.Minecraft.func_71407_l(Minecraft.java:1602) [bao.class:?]
	at net.minecraft.client.Minecraft.func_71411_J(Minecraft.java:973) [bao.class:?]
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:5110) [bao.class:?]
	at net.minecraft.client.main.Main.main(SourceFile:148) [Main.class:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_421]
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_421]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_421]
	at java.lang.reflect.Method.invoke(Unknown Source) ~[?:1.8.0_421]
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135) [launchwrapper-1.12.jar:?]
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28) [launchwrapper-1.12.jar:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_421]
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_421]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_421]
	at java.lang.reflect.Method.invoke(Unknown Source) ~[?:1.8.0_421]
	at org.multimc.onesix.OneSixLauncher.launchWithMainClass(OneSixLauncher.java:243) [NewLaunch.jar:?]
	at org.multimc.onesix.OneSixLauncher.launch(OneSixLauncher.java:278) [NewLaunch.jar:?]
	at org.multimc.EntryPoint.listen(EntryPoint.java:143) [NewLaunch.jar:?]
	at org.multimc.EntryPoint.main(EntryPoint.java:34) [NewLaunch.jar:?]
```

**Comment by reobf** [comment]
> And get this in console time by time. But again - not your mod
> 
> ```
> java.util.concurrent.CancellationException
> 	at java.util.concurrent.CompletableFuture.cancel(Unknown Source) [?:1.8.0_421]
> 	at me.jellysquid.mods.sodium.client.render.chunk.compile.ChunkBuilder.stopWorkers(ChunkBuilder.java:158) [ChunkBuilder.class:?]
> 	at me.jellysquid.mods.sodium.client.render.chunk.ChunkRenderManager.destroy(ChunkRenderManager.java:633) [ChunkRenderManager.class:?]
> 	at me.jellysquid.mods.sodium.client.render.SodiumWorldRenderer.initRenderer(SodiumWorldRenderer.java:296) [SodiumWorldRenderer.class:?]
> 	at me.jellysquid.mods.sodium.client.render.SodiumWorldRenderer.reload(SodiumWorldRenderer.java:291) [SodiumWorldRenderer.class:?]
> 	at net.minecraft.client.renderer.RenderGlobal.reload(RenderGlobal.java:5744) [bma.class:?]
> 	at net.minecraft.client.renderer.RenderGlobal.handler$zfk000$angelica$onReload(RenderGlobal.java:5737) [bma.class:?]
> 	at net.minecraft.client.renderer.RenderGlobal.func_72712_a(RenderGlobal.java:5766) [bma.class:?]
> 	at net.minecraft.client.renderer.RenderGlobal.func_72732_a(RenderGlobal.java:294) [bma.class:?]
> 	at net.minecraft.client.Minecraft.func_71353_a(Minecraft.java:2216) [bao.class:?]
> 	at net.minecraft.client.Minecraft.func_71403_a(Minecraft.java:2146) [bao.class:?]
> 	at net.minecraft.client.network.NetHandlerPlayClient.func_147280_a(NetHandlerPlayClient.java:874) [bjb.class:?]
> 	at net.minecraft.network.play.server.S07PacketRespawn.func_148833_a(SourceFile:32) [hs.class:?]
> 	at net.minecraft.network.play.server.S07PacketRespawn.func_148833_a(SourceFile:13) [hs.class:?]
> 	at net.minecraft.network.NetworkManager.func_74428_b(NetworkManager.java:212) [ej.class:?]
> 	at net.minecraft.client.multiplayer.PlayerControllerMP.func_78765_e(PlayerControllerMP.java:273) [bje.class:?]
> 	at net.minecraft.client.Minecraft.func_71407_l(Minecraft.java:1602) [bao.class:?]
> 	at net.minecraft.client.Minecraft.func_71411_J(Minecraft.java:973) [bao.class:?]
> 	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:5110) [bao.class:?]
> 	at net.minecraft.client.main.Main.main(SourceFile:148) [Main.class:?]
> 	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_421]
> 	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_421]
> 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_421]
> 	at java.lang.reflect.Method.invoke(Unknown Source) ~[?:1.8.0_421]
> 	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135) [launchwrapper-1.12.jar:?]
> 	at net.minecraft.launchwrapper.Launch.main(Launch.java:28) [launchwrapper-1.12.jar:?]
> 	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_421]
> 	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_421]
> 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_421]
> 	at java.lang.reflect.Method.invoke(Unknown Source) ~[?:1.8.0_421]
> 	at org.multimc.onesix.OneSixLauncher.launchWithMainClass(OneSixLauncher.java:243) [NewLaunch.jar:?]
> 	at org.multimc.onesix.OneSixLauncher.launch(OneSixLauncher.java:278) [NewLaunch.jar:?]
> 	at org.multimc.EntryPoint.listen(EntryPoint.java:143) [NewLaunch.jar:?]
> 	at org.multimc.EntryPoint.main(EntryPoint.java:34) [NewLaunch.jar:?]
> ```

Sodium-Anglica
That mod is buggy, never mind.

**Comment by reobf** [comment]
When it try this savefile the log says 
`[17:52:01] [Server thread/ERROR] [fml.ModTracker]:  This world was saved with mod TwistSpaceTechnology which appears to be missing, things may not work well`

I think TwistSpaceTechnology currently has no build for 270 now...
How is that possible..?

**Comment by TimberDimber** [comment]
Uh... it's our own build for 270+

**Comment by reobf** [comment]
Wow amazing

**Comment by reobf** [comment]
I am testing with standard 270-beta-2 build+my mod in Single Player mode.
Actually TPS seems okay...?

**Comment by reobf** [comment]
Well maybe the problem is fixed in standard 270-beta-2 build
I will check change log if some issue does exist.

**Comment by evgengoldwar** [comment]
> Well maybe the problem is fixed in standard 270-beta-2 build I will check GTNH changelog if some issue does exist.

After your fix, the tps has improved. Still have some drops but tps stays around 9-13 mc and I can't say for sure what is causing it, your mod or my wrong ae build.

**Comment by evgengoldwar** [comment]
Thanks for the corrections and quick replies. If further lags can be better tracked after upgrading to a newer nightly I'll report on it

**Comment by reobf** [comment]
![2024-10-19_18 46 28](https://github.com/user-attachments/assets/f12a73cb-4ca4-4e7d-b314-6ab7c2150fb8)
![2024-10-19_18 46 46](https://github.com/user-attachments/assets/b6048b2d-7301-4c52-885a-cb4ab2eb2f9f)
I use evgengoldwar's id in offline mode to make SU chunkloding works.

**Comment by reobf** [comment]
TPS is stable

**Comment by TimberDimber** [comment]
![image](https://github.com/user-attachments/assets/ba58ae82-aaaa-4527-bb28-168aab888880)

**Comment by TimberDimber** [comment]
Not so stable 😅

**Comment by evgengoldwar** [comment]
> ![2024-10-19_18 46 28](https://private-user-images.githubusercontent.com/117543727/378072483-f12a73cb-4ca4-4e7d-b314-6ab7c2150fb8.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjkzMzUyMTMsIm5iZiI6MTcyOTMzNDkxMywicGF0aCI6Ii8xMTc1NDM3MjcvMzc4MDcyNDgzLWYxMmE3M2NiLTRjYTQtNGU3ZC1iMzE0LTZhYjdjMjE1MGZiOC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMDE5JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTAxOVQxMDQ4MzNaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1hNjUzZjY4MmUxMWI2NjNkNzVhYjg2NmZkZGJiNTNjYWI3Njk3NjY1NTZhYTY3MTI5OTNkMTQwYjY3NzU2OGU5JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.nWKsvmyrq2UtqRGITeuftPnn0VWRrHZZL48q06U38tY) ![2024-10-19_18 46 46](https://private-user-images.githubusercontent.com/117543727/378072488-b6048b2d-7301-4c52-885a-cb4ab2eb2f9f.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjkzMzUyMTMsIm5iZiI6MTcyOTMzNDkxMywicGF0aCI6Ii8xMTc1NDM3MjcvMzc4MDcyNDg4LWI2MDQ4YjJkLTczMDEtNGM1Mi04ODVhLWNiNGFiMmViMmY5Zi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMDE5JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTAxOVQxMDQ4MzNaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1kOGUwY2RjNDFlZWIyMWIwNjM5YzA0OTU1NDUwMTVlMmNmNjE2ODRlY2NjNTAyN2NmYWY5MDE4M2Y1ODlmZjI5JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.YwHQS0xOAvoMFtl2EKf7iKWLULYli3BNKf3ITMYjsno) I use evgengoldwar's id in offline mode to make SU chunkloding works.

3 tps value can be increased, but I don't think it's related to your mod.

**Comment by evgengoldwar** [comment]
> 3 tps value can be increased, but I don't think it's related to your mod.

**Comment by reobf** [comment]
Most of lag are caused by Downlink Module

**Comment by reobf** [comment]
https://spark.lucko.me/hmceM6KEPG

**Comment by evgengoldwar** [comment]
> https://spark.lucko.me/hmceM6KEPG

https://spark.lucko.me/3UEWqYfz66

That's how I have it now.

**Comment by evgengoldwar** [comment]
As I wrote above everything is normal only 3 value tps sometimes rises but I will not say for sure that it is because of your mod so I think so far everything is normal

**Comment by reobf** [comment]
Oh...
If you are using your own 270 build with TwistSpaceTechnology
It should be early 270 nightly, before the Great Renaming PR of GT5U.
So actually you are using the mod file without GTNH270 suffix?

**Comment by reobf** [comment]
That Great Renaming PR is such a compatibility breaker.

**Comment by evgengoldwar** [comment]
![image](https://github.com/user-attachments/assets/c17753b5-eff8-4263-af8a-5064fcd7aafc)

I'm using this

> Oh... If you are using your own 270 build with TwistSpaceTechnology It should be early 270 nightly, before the Great Renaming PR of GT5U. So actually you are using the mod file without GTNH270 suffix?

**Comment by TimberDimber** [comment]
> That Great Renaming PR is such a compatibility breaker.

![image](https://github.com/user-attachments/assets/c74258ef-efbd-4bcf-a153-2b3dd167c50a)
Like this?

**Comment by reobf** [comment]
> > That Great Renaming PR is such a compatibility breaker.
> 
> ![image](https://private-user-images.githubusercontent.com/22298720/378073335-c74258ef-efbd-4bcf-a153-2b3dd167c50a.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjkzMzU4NTksIm5iZiI6MTcyOTMzNTU1OSwicGF0aCI6Ii8yMjI5ODcyMC8zNzgwNzMzMzUtYzc0MjU4ZWYtZWZiZC00YmNmLWExNTMtMmIzZGQxNjdjNTBhLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEwMTklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMDE5VDEwNTkxOVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWFiYzFiMDBlNWU0MmMwM2JkY2UwYmY3OTFiY2MwMzk2NTdhOTgxODYzOTBlOGY3YmYwOWNmMDU2MmQyZjUyNTgmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.DbAmLrxESSCpHscsJB1KVzNVriT5ZHojjyXrM5yOM7M) Like this?

Yup

**Comment by TimberDimber** [comment]
So, then with 270 suffix

**Comment by reobf** [comment]
So you guys literally build a TST mod working on 270？

**Comment by evgengoldwar** [comment]
> So you guys literally build a TST mod working on 270？

Yeah, except the logic of overclocking multiblocks is broken

**Comment by reobf** [comment]
That's a big project.

**Comment by TimberDimber** [comment]
Only overclocking and EU usage in some multis broken, but 80% work fine

**Comment by evgengoldwar** [comment]
> That's a big project.

Nxer himself has already fixed almost everything to go to 270, but there are still a couple of crashes from his own multiblocks and a broken overclock that we fixed

**Comment by reobf** [comment]
That's why I'm unwilling to create much multiblocks.
They break almost every time there's a big update.

**Comment by evgengoldwar** [comment]
Yea

**Comment by TimberDimber** [comment]
They just overwrite overclock logic and TST not adapted for it.

**Comment by reobf** [comment]
Sure
